### ISSUE TITLE
Github action for cmake build

### ISSUE THREAD

**Issue by phynxinferno** [Byte-Sized-Games/logJam#1]
- Add build resources for MacOS ARM(brandon), MacOS x64(kutschke), Linux x64(michael & phoenix)
- Set up github template action cmake build multi-platform and use the respective resources for each one

**Comment by gecotron** [comment]
Seeing as this project is no longer using cmake and likely won't in the future, I am closing this issue until further notice

**Comment by phynxinferno** [comment]
same thing should work with just

**Comment by phynxinferno** [comment]
done :3
