### ISSUE TITLE
Move gamestate to a separate dir

### ISSUE THREAD

**Issue by gecotron** [Byte-Sized-Games/logJam#17]
I can't do shit on the main file with constant merge conflicts interrupting work. Please move the GameState struct and runtime module to a separate file or directory

**Comment by phynxinferno** [comment]
Runtime and gamestate should be part of the main file bc that's where the execution happens. That's their scope. You shouldn't be getting merge conflicts though if you're changing different parts of the file. Maybe a weird git thing

**Comment by gecotron** [comment]
Fair enough
