### ISSUE TITLE
get raylib to render something

### ISSUE THREAD

**Issue by phynxinferno** [Byte-Sized-Games/logJam#2]

**Comment by gecotron** [comment]
I have a basic working render on my end currently. It can't do inputs, but it manages stages (scenes & game state) through an enum and switch statement in the main function. I'll either commit or send a pull request in a bit to finalize basic rendering. Input won't be a guarantee though, and will probably be a separate issue

**Comment by phynxinferno** [comment]
raylib is rendering something. thanks michael :3

**Comment by gecotron** [comment]
sorry to comment on a closed issue, but I just wanted to note that raylib is now rendering something slightly more meaningful
