### ISSUE TITLE
No Spec/Contributing Guide

### ISSUE THREAD

**Issue by gecotron** [Byte-Sized-Games/logJam#4]
As of writing we have no particular specification for how we write our code to this project, nor a guide on contributing, but for our sakes they count as the same thing. I would propose we construct some from of guide on how we're writing / commenting this code so that the project looks consistent and readable

**Comment by Ishita777** [comment]
I would like to help you with this issue, can you please extend the description a bit.

**Comment by phynxinferno** [comment]
honestly comments are useless in 99% of cases. commenting spec should be only when something is confusing/not apparent
we should enforce a variable naming spec tho. I think I can set up a github action to point out/fix case issues at least

**Comment by phynxinferno** [comment]
fixed by @Ishita777
