### ISSUE TITLE
proposal: switch to cmake to reduce headaches

### ISSUE THREAD

**Issue by phynxinferno** [Byte-Sized-Games/logJam#7]
Cmake works better with linting, easier to set up on brandon's computer, and does library management, etc. for us.

**Comment by gecotron** [comment]
I can see it being useful for our end goal. Why not

**Comment by gecotron** [comment]
I'll see about setting it up

**Comment by gecotron** [comment]
Closed as of commit [dd52043](https://github.com/Byte-Sized-Games/logJam/commit/dd5204301df17957025c624ffd9a4a7d0ced8b2a). We now use cmake to build. Switching github actions will follow, possibly in a different commit
