### ISSUE TITLE
Github Action Broekn.

### ISSUE THREAD

**Issue by gecotron** [Byte-Sized-Games/logJam#9]
Yeah. I never worked with this stuff. I have no clue how it should work.

**Comment by gecotron** [comment]
Im gonna give it a shot

**Comment by gecotron** [comment]
It is still broken, but more functional than before....

**Comment by phynxinferno** [comment]
fart

**Comment by gecotron** [comment]
Looks like windows builds fine, but on Linux it can't find the `randr` library. I'm currently looking at how to get that fixed

**Comment by phynxinferno** [comment]
closed as part of the rust migration 🦀
